name: Install BSK-RL
description: Install BSK-RL using Basilisk wheels
inputs:
  python-version:
    required: true
    type: string
    default: "3.11"
  pip-options:
    type: string
    default: "all"
runs:
  using: "composite"
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.python-version }}
  - name: Find artifact run
    shell: bash
    run: |
      sudo apt-get install jq
      export RUN_ID=$(
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/AVSLab/basilisk/actions/runs?status=completed&per_page=100" | 
        jq -r '.workflow_runs[] | select(.name == "Pull Request Closed") | .id' | 
        head -n 1
      )
      echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
  - name: Pull artifacts
    uses: actions/download-artifact@v4
    with:
      name: basilisk-wheels_ubuntu-22.04_python${{ inputs.python-version }}
      repository: AVSLab/basilisk
      run-id: ${{ env.RUN_ID }}
      github-token: ${{ github.token }}
  - name: Install Basilisk from wheels
    shell: bash
    run: |
      pip install *asilisk*.whl
      bskLargeData
  - name: Install BSK-RL
    shell: bash
    run: pip install -e '.[${{ inputs.pip-options }}]' && finish_install
